# Server port (different from product-service!)
server.port=8082

# Application name
spring.application.name=cart-service

# H2 Database Configuration ? SEPARATE database!
spring.datasource.url=jdbc:h2:mem:cartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# ACTIVE MQ
# =========================
spring.activemq.broker-url=${SPRING_ACTIVEMQ_BROKER_URL:tcp://activemq:61616}
spring.activemq.user=admin
spring.activemq.password=admin

# =========================
# EUREKA CLIENT
# =========================
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:defaultZone: http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# ACTUATOR (IMPORTANT POUR HEALTH CHECK)
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always